image: python:3.11

services:
  - name: docker:20.10.7-dind


stages:
  - build
  - test
  - dockerise

cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  - python3 -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  when: manual  # This ensures the build job is only triggered manually

test:
  stage: test
  script:
    - source venv/bin/activate
    - python manage.py test --exclude-tag=db
  when: manual  # This ensures the test job is only triggered manually

dockerise:
  stage: dockerise
  script:
    - docker build -t oussematrimech/employeeapp:latest .
  only:
    - main
  when: on_success  # Runs when the pipeline reaches the dockerise stage
