image: python:3.11

stages:
  - build
  - test
  - dockerise
cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  # Create and activate virtual environment
  - python3 -m venv venv
  - source venv/bin/activate
  # Install Docker CLI if needed for DinD

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    # Install dependencies
    - pip install --upgrade pip
    - pip install -r requirements.txt

test:
  stage: test
  script:
    # Activate virtual environment in the test stage
    - source venv/bin/activate
    # Run tests without database (adjust tests to not require DB access)
    - python manage.py test --exclude-tag=db


build_image:
  stage: dockerise
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker logout

