image: python:3.11

stages:
  - build
  - test
  - dockerise

services:
  - docker:latest  # Use Docker service for the build

cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  - python3 -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - source venv/bin/activate
    - python manage.py test --exclude-tag=db

dockerise:
  stage: dockerise
  script:
    - docker build -t oussematrimech/employeeapp:latest .
  only:
    - main

# Docker socket mount
docker:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
