image: docker:lastest
services:
  - docker:dind

stages:
  - Build

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build_job:
  stage: Build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker logout