image: python:3.11

services:
  - name: docker:20.10.7-dind  # Docker-in-Docker service for building images

stages:
  - build
  - test
  - dockerise

cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  # Set up virtual environment
  - python3 -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - source venv/bin/activate
    - python manage.py test --exclude-tag=db

dockerise:
  stage: dockerise
  script:
    # Ensure Docker is running properly and build the image
    - docker info  # Verify Docker connectivity
    - docker build -t oussematrimech/employeeapp:latest .
  only:
    - main

# Ensure Docker is able to run
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_DRIVER: "overlay2"
