image: python:3.11

stages:
  - build
  - test

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python manage.py migrate

test:
  stage: test
  script:
    - python manage.py test
