image: python:3.11

services:
  - name: docker:20.10.7-dind  # Docker-in-Docker service

stages:
  - build
  - test
  - dockerise

cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  - python3 -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  when: manual
test:
  stage: test
  script:
    - source venv/bin/activate
    - python manage.py test --exclude-tag=db
  when: manual
dockerise:
  stage: dockerise
  script:
    - docker info  # Check if Docker service is working
    - docker build -t oussematrimech/employeeapp:latest .
  only:
    - main
