image: python:3.11

stages:
  - build
  - test
  - dockerise
# Cache to persist dependencies and venv
cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  # Create and activate virtual environment
  - python3 -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    # Install dependencies
    - pip install --upgrade pip
    - pip install -r requirements.txt
    # Ensure code quality with linting (optional, if linter is used)
    # - flake8 .

test:
  stage: test
  script:
    # Activate virtual environment in the test stage
    - source venv/bin/activate
    # Run tests without database (adjust tests to not require DB access)
    - python manage.py test --exclude-tag=db
dockerise:
  stage: dockerise
  script:
    - docker build -t oussematrimech/employeeapp:latest .
