image: python:3.11

services:
  - docker:20.10.7-dind  # Docker-in-Docker service

stages:
  - build
  - test
  - dockerise

cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  # Create and activate virtual environment
  - python3 -m venv venv
  - source venv/bin/activate
  # Install Docker CLI if needed for DinD
  - apt-get update && apt-get install -y docker.io
  - chmod 666 /var/run/docker.sock

build:
  stage: build
  script:
    # Install dependencies
    - pip install --upgrade pip
    - pip install -r requirements.txt
  when: manual
test:
  stage: test
  script:
    # Activate virtual environment in the test stage
    - source venv/bin/activate
    # Run tests without database (adjust tests to not require DB access)
    - python manage.py test --exclude-tag=db
  when: manual
dockerise:
  stage: dockerise
  script:
    # Build the Docker image
    - docker build -t oussematrimech/employeeapp:latest .
    # Push the image to Docker Hub



