image: python:3.11

services:
  - docker:19.03.12-dind  # Docker-in-Docker service

stages:
  - build
  - test
  - dockerise

cache:
  paths:
    - venv/
    - .cache/pip/

before_script:
  # Create and activate virtual environment
  - python3 -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    # Install dependencies
    - pip install --upgrade pip
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - source venv/bin/activate
    - python manage.py test --exclude-tag=db

dockerise:
  stage: dockerise
  script:
    - docker build -t oussematrimech/employeeapp:latest .
  only:
    - main
