stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - py -m venv venv  # Create virtual environment
    - source venv/bin/activate  # Activate virtual environment
    - pip install -r requirements.txt  # Install dependencies

test:
  stage: test
  script:
    - source venv/bin/activate  # Activate virtual environment
    - python manage.py test  # Run tests

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
