# Generated by Django 5.1.2 on 2024-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_employee_employmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.IntegerField(default=1),
        ),
    ]
