# Generated by Django 5.1.2 on 2024-12-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_type', models.CharField(max_length=100)),
                ('amenagement_type', models.CharField(max_length=255)),
                ('amenagement_state', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=50)),
                ('evaluation_date', models.DateField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicaps', to='EmployeeApp.department')),
                ('employe_promotionne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicaps', to='EmployeeApp.employee')),
            ],
        ),
    ]
