# Generated by Django 5.1.2 on 2024-12-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_handicap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handicap',
            old_name='employe_promotionne',
            new_name='employee',
        ),
    ]
